[book]
authors = ["dalance"]
language = "en"
multilingual = false
src = "src"
title = "The Veryl Hardware Description Language"

[build]
extra-watch-dirs = ["po"]

[preprocessor.curl]
command = "curl -OL https://raw.githubusercontent.com/dalance/veryl/master/crates/parser/veryl.par"

[preprocessor.veryl]

[preprocessor.gettext]
after = ["links"]

[output.html]
curly-quotes = true
additional-css = [
  "theme/css/language-picker.css",
]
additional-js = [
  "mode-veryl.js",
  "editor.js",
]

[output.html.fold]
enable = true
level  = 1

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = false
